### ISSUE TITLE
Customer menu location 

### ISSUE THREAD

**Issue by MwMaki** [malkhafaji/pure_portal#83]
1- In AR the logo, flag and menu should be on the right side while . name and balances on left side 

<img width="1509" alt="screen shot 2019-02-19 at 11 37 52 am" src="https://user-images.githubusercontent.com/22043245/53035345-d2268c80-343a-11e9-9a21-ec6cb3d9266f.png">

**Comment by aqattan** [comment]
PR submitted and merged
